### ISSUE TITLE
makensis is automatically executed when clicking on file in sidebar

### ISSUE THREAD

**Issue by jondyowens** [idleberg/vscode-nsis#13]
When clicking on a .nsi file in the file explorer sidebar, makensis automatically compiles my script and generates the installer executable file. Is there any way to suppress this behavior?

**Comment by idleberg** [comment]
Can you tell whether it's the build functionality provided by the package or a VSCode task that causes this? If you're unsure, please post a screenshot.

**Comment by jondyowens** [comment]
![before_clicking](https://user-images.githubusercontent.com/11183033/75619919-10b75280-5b37-11ea-8697-8e458fc2155a.png)
![after_clicking](https://user-images.githubusercontent.com/11183033/75619920-11e87f80-5b37-11ea-9c7e-a5a7f0d4ac37.png)

Whenever I click on an .nsh or .nsi file that has !system commands or Sections, it executes those.

The only extensions I have installed are:
C/C++
NSIS
Output Colorizer
Remote - WSL
Rust

**Comment by idleberg** [comment]
I think the problem is caused by the default linter. To fix this, open the VSCode settings, jump to Extensions/NSIS/Preprocess Mode (or search for "nsis linter") and set the mode to "Safe PPO". If you can confirm this fixes the problem on your end, I will make this the new default in the next version!

**Comment by jondyowens** [comment]
Yea that fixes it for me. Thanks for the help!
