### ISSUE TITLE
Cant get through proxy.

### ISSUE THREAD

**Issue by bearslumber** [idleberg/vscode-nsis#2]
Hi

I can't get access to the VSCode git repositories from my proxy firewall.

Can you please make a .vsix available so that I can install it locally?

All help greatly appreciated.

Bearslumber

**Comment by idleberg** [comment]
I'm not sure I want to double the work maintaining two files, `package.json` and `extension.vsixmanifest`. If you know of any Node scripts that read the `package.json` to create the manifest, I can look into it (my Google search was unsuccesful)

In the meantime, why don't you download the ZIP file and extract it to your extensions folder?

**Comment by bearslumber** [comment]
Thanks for your prompt reply.

I totally understand.

Your suggestion worked, so thank you very much.

Being a newbie, I'm still finding my way round. The web page suggests installations by .vsix so I asked that question. 

I looked at some other .vsix files and they don't seem too onerous. If you can point me to the rules on how to create them, I will try and create one for your package and if it works I'll let you know, and see whether it is worth making it available. No promises though.

Thanks again

Bearslumber

**Comment by idleberg** [comment]
Creating VSIX is [well-documented](https://msdn.microsoft.com/en-us/library/ff407026.aspx), but that's not the point. I'm interested in automatic creation of VSIX packages, since I'm not going to edit XML for all my extensions manually.

I've found [two Node packages](https://www.npmjs.com/search?q=TFX-CLI) to do that, but maybe using `vsce` is [the way to go](https://code.visualstudio.com/docs/tools/vscecli#_packaging-extensions). I will look into it!

**Comment by idleberg** [comment]
Please give this a try: [nsis-0.7.2.vsix](https://github.com/idleberg/vscode-nsis/releases/tag/0.7.2)

**Comment by bearslumber** [comment]
Hi Jan,

That worked a treat.

Many thanks and much appreciated.

Bearslumber
