### ISSUE TITLE
Compile errors for valid lines

### ISSUE THREAD

**Issue by jahir** [idleberg/vscode-nsis#29]
Using vscode-nsis 3.41.0 with VS Code:
```
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043
```
makensis is not in the PATH, so I set this:
`"nsis.compiler.pathToMakensis": "C:\\Program Files (x86)\\NSIS\\makensis.exe"`

Editing works fine, but I can not compile. vscode-nsis shows an error in most if my nsi/nsh files. Compiling with MakeNSISW works just fine and without any errors or even warnings.

It starts with this one:
```
!tempfile git_revparse
!system "git rev-parse --short HEAD > ${git_revparse}"
!define /file GIT_COMMIT_ID "${git_revparse}"
!delfile "${git_revparse}"
```
where it says `!define /file: file not found ("${git_revparse}")`

but continues with simple stuff:
`${If} ${Errors}` -> `Invalid command: "${If}"`
`!insertmacro MUI_HEADER_TEXT "bla foo bar" ""` -> `!insertmacro: macro named "MUI_HEADER_TEXT" not found!`
`nsArray::Clear Models` -> `Plugin not found, cannot call nsArray::Clear`

I can hardly believe this is the current state, so it may be related to my setup or my script files. I have a single `nsi` file that `!include`s a bunch of `nsh` files.

Any idea where I should look?

**Comment by idleberg** [comment]
Is the behaviour the same when you compile your script directly from the command-line?

**Comment by jahir** [comment]
Yes, makensis runs fine, just as makensisw:
```
D:\ProjectX>"c:\Program Files (x86)\NSIS\makensis.exe" ProjectX.nsi
Processing config: c:\Program Files (x86)\NSIS\nsisconf.nsh
Processing script file: "ProjectX.nsi" (ACP)

Processed 1 file, writing output (x86-unicode):

Output: "D:\ProjectX\out\ProjectX_Setup.exe"
Install: 9 pages (576 bytes), 18 sections (2 required) (37296 bytes), 3150 instructions (88200 bytes), 3122 strings (100442 bytes), 1 language table (318 bytes).
Datablock optimizer saved 154546 bytes (~0.5%).

Using zlib compression.

EXE header size:              131072 / 39424 bytes
Install code:                 227300 / 227296 bytes
Install data:               28373592 / 28528138 bytes
CRC (0x9B4B7714):                  4 / 4 bytes

Total size:                 28731968 / 28794862 bytes (99.7%)
```

Assuming that vscode-nsis runs makensis without any additional parameters, I wonder where it gets these errors from that are shown in VSC.

**Comment by idleberg** [comment]
I will take a closer look, but I won't be able to before next week

**Comment by idleberg** [comment]
> It starts with this one:
> 
> ```nsis
> !tempfile git_revparse
> !system "git rev-parse --short HEAD > ${git_revparse}"
> !define /file GIT_COMMIT_ID "${git_revparse}"
> !delfile "${git_revparse}"
> ```
> 
> where it says !define /file: file not found ("${git_revparse}")

I cannot reproduce this. While I see this error highlighted by diagnostics, the script compiles fine. Since I'm not testing this in Windows, please make sure `git` is properly installed (i.e. does Git for Windows run in PowerShell or the old Command Prompt or just in Git Bash?)

> `${If} ${Errors} -> Invalid command: "${If}"``

Did you include `LogicLib`?


> !insertmacro MUI_HEADER_TEXT "bla foo bar" "" -> !insertmacro: macro named "MUI_HEADER_TEXT" not found!

Did you include `MUI2`? IIRC, the macros also need to be defined in the correct order


> nsArray::Clear Models -> Plugin not found, cannot call nsArray::Clear

Is the plugin installed at the expected location?

**Comment by jantograaf** [comment]
I can reproduce this error on a Windows system. It seems to be related to the fact that the file that is being 'loaded' in the !define does not exist at complation time.

My specific script would create a file by using a `!system` command and then use a `!define` to use the contents of that file. That always seemed to fail compilation unless I created a blank placeholder file with the same name in the location mentioned in the `!define /file`. The script would compile without warnings after that.

Example script:
```
!system 'CertUtil -hashfile "${TOOLKITFILE}" MD5 | find /i /v "md5" | find /i /v "certutil" > C:\TMP\TOOLKITHASH.TXT'
!define /file TOOLKITHASH "C:\TMP\TOOLKITHASH.TXT"
!echo 'Toolkit hash seems to be : ${TOOLKITHASH}'
```
Since this doesn't work the **first** time (because of the TXT-file not existing when the pre-processor checks the code), I added the following two lines which would delete the file and _touch_ an empty one after each compilation. Not the cleanest solution, but it works.
```
!system 'del C:\TMP\TOOLKITHASH.TXT'
!system '.>C:\TMP\TOOLKITHASH.TXT 2>NUL'
```
